---
# Common packages

- name: Install common packages
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - curl
    - gcc
    - git
    - make
    - mosh
    - nmap
    - tcpdump
    - tmux
    - vim
    - wget
    - zsh

- name: Install Watchman playbook missing dependencies
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - libssl-dev

- name: Set zsh as default shell
  user: name=chantra shell=/usr/bin/zsh

